apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  #- secret.enc.yaml
  - service-clusterip.yaml
  - deployment.yaml
  - ingress.yaml