apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - service.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage-bookmarks
    files:
      - bookmarks.yaml
    options:
      labels:
        app: homepage
  - name: homepage-services
    files:
      - services.yaml
    options:
      labels:
        app: homepage