apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-config-pv
  namespace: homepage
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/apps/homepage
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime