apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: homepage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: homepage-config-pv
  storageClassName: ""