apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/apps/fresh-rss
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-extensions-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/apps/fresh-rss/extensions
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime