apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diyhue-ingress
  namespace: diyhue
spec:
  ingressClassName: nginx
  rules:
  - host: diyhue.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diyhue-service
            port:
              number: 80
