apiVersion: v1
kind: Service
metadata:
  name: diyhue-service
  namespace: diyhue
spec:
  selector:
    app: diyhue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.145