apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgres
  name: postgres-data
spec:
  storageClassName: ""
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
