apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:release
          ports:
            - containerPort: 2283
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: DB_HOSTNAME
              value: "postgres.postgres.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            # - name: IMMICH_MACHINE_LEARNING_URL
            #   value: "http://immich-machine-learning:3003"              
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: DB_DATABASE_NAME
            - name: REDIS_HOSTNAME
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: JWT_SECRET
            - name: UPLOAD_LOCATION
              value: "/usr/src/app/upload"
          volumeMounts:
            - name: immich-data
              mountPath: /usr/src/app/upload
          livenessProbe:
            httpGet:
              path: /server-info/ping
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /server-info/ping
              port: 2283
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-data
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: immich-machine-learning
#   namespace: immich
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: immich-machine-learning
#   template:
#     metadata:
#       labels:
#         app: immich-machine-learning
#     spec:
#       nodeSelector:
#         kubernetes.io/hostname: worker-02
#       containers:
#         - name: immich-machine-learning
#           image: ghcr.io/immich-app/immich-machine-learning:release
#           ports:
#             - containerPort: 3003
#           env:
#             - name: MACHINE_LEARNING_CACHE_FOLDER
#               value: "/cache"
#           volumeMounts:
#             - name: ml-cache
#               mountPath: /cache
#       volumes:
#         - name: ml-cache
#           emptyDir: {}