apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:zrrJ79pEznbMCiUM,iv:5HB2YESoHZu9bsq5LlsPghZ+f6ERDX1fR52IINhNPz8=,tag:SO9e8HQR5ftZ5NQPFHuz1g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:DwJD2GvY,iv:JhNAhDLPYZMNwh68nw5szWHfUFijJ0GUScsVo6hN3gs=,tag:mawRLLb2EDgYxCzWfKCOYw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:vCbS4PWr,iv:qTjvL5HqpUlHHrAPkLsifc1lLbIrk0DODK1POKap3DE=,tag:lCby9LvFet8Gu9HDC27Tfg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:9wxtKBomSzzuAZAld2VEoeZuikDEtQ==,iv:M2ZIFEL8E6jaDUafoJHGqrnlhL2jtX8KurQ+4QvQHqg=,tag:ODL1d+FINS089Zrl5I4ahg==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTTBWK3F3SnpoYmFTeEVR
            ZHZqWVMvcTQ4WEQ0cXN2WlRLRjU5amU3YTE0Ck9RMWUzUXJmSUFUSkIzeVBMV2tp
            aG1pSzNzUUtUWlBKckd4bVY0OHBUakkKLS0tIGVPVkZpS3AwbFR5ajFrekZaYUxy
            d0c0S1dYb0lKcktQYnJKcDFWSCtsVk0KyRIEixg1Ouf1RiJ1FMVxqSun7YCmyQ4z
            KO7zHsXWM1JimRHiHuD0w1c5Wn6MY6uDLgzekl3s503eIIITPQzSKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T03:20:04Z"
    mac: ENC[AES256_GCM,data:5V486myxFimvX8euKdaOV/yMGpAyuA3iwFhyfzaAd7d98m4GBWmfVcP1jtG7aeELWuzgL2wQSpX3mzb7RkPbT/3tyRVhYIn4z0gmUzU5nSHXiXaOg63SN/oaH6JvDVDzwVfj4bqYjOXMTuHg7E0Wyr/GZ2wHDHoGYUIGGPWeMKc=,iv:oBXsf7t3SrBJ9cKNBvtgoKcO1ht4B5TVU7R0hGYyGEg=,tag:sG1siUHoI4IYGw6R5DQBxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
