apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  interval: 24h
  path: ./kubernetes/apps/audiobookshelf
  prune: true
  targetNamespace: audiobookshelf
  sourceRef:
    kind: GitRepository
    name: flux-system