apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ddns-updater
  namespace: flux-system
spec:
  interval: 24h
  path: ./kubernetes/architecture/ddns-updater/base
  prune: true
  targetNamespace: ddns-updater
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age