apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flaresolver
  namespace: flux-system
spec:
  interval: 24h
  path: ./kubernetes/apps/flaresolver
  prune: true
  targetNamespace: flaresolver
  sourceRef:
    kind: GitRepository
    name: flux-system