apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  interval: 24h
  path: ./kubernetes/architecture/intel-gpu-plugin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
