apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpn-qbittorrent
  namespace: flux-system
spec:
  interval: 24h
  path: ./kubernetes/apps/qbittorrent
  prune: true
  targetNamespace: vpn-qbittorrent
  sourceRef:
    kind: GitRepository
    name: flux-system