apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wg-easy
  namespace: flux-system
spec:
  interval: 24h
  path: ./kubernetes/apps/wireguard-easy
  prune: true
  targetNamespace: wg-easy
  sourceRef:
    kind: GitRepository
    name: flux-system  
