apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/ghost
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime