apiVersion: v1
kind: Secret
metadata:
    name: ghost-db-secret
    namespace: ghost
type: Opaque
stringData:
    database__connection__user: ENC[AES256_GCM,data:jQcFo0g=,iv:bRlIhudAStMvui8VN89cL96DWwS6ZK3Q6goAEsdM3VY=,tag:hSCsk1UtduMql/Q4uAgKtQ==,type:str]
    database__connection__password: ENC[AES256_GCM,data:opvpldulAmHIup+njk8=,iv:kHMfrQuqEkZUGMcBR+tgfPpNesIQN8ROtG2GyJ+Ulg8=,tag:6gCwYgoGtd2WgS1mhIEKWg==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL0dTYXJtS1pHQWtqczRT
            Mnd5eFEvbEgrc1lPMkhFSEdHRzVoUFlvNGdJCjV4YkswL3hCYlFqREhiQXlaZGpp
            eWJnQldmWElDSVorcm9aY3dzajFiMkEKLS0tIHFoZnAveTZKT0ZKbzV0cm5PK01X
            ZUJDeXJ1dk1vOWs1bUlnRXVMRktWWU0KXwiwaQLKqtK1NR8tWExys5eAjQBemnfW
            0UMH6/rQmv+zTgFfxLA5mC3ffCxmypGnHjqWgxD2Z+3y8GbCrquLIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T14:50:38Z"
    mac: ENC[AES256_GCM,data:7g83TvtCSlb0rU8QTZVdIgIJSU2p4zoeo5xWmrOJWcqDwUZWard2O8RkX7RltVTKF1PITVOZxVgWmqYtMXoFe/IaM3Blj9hRRkjv4RKbKK5v58DrwDVWJVNNhgMaz0kfdE3JqDcjmvleZNyVlR9J7klIe8hB9BVgLoOQ3nj+GqE=,iv:ic/iCIp5TuSO4zOqtnw5aIzhJOs7aIDjH64TFoharvU=,tag:/74gVFvHVZz34bb3PTjzoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
