apiVersion: v1
kind: Secret
metadata:
    name: ghost-db-secret
    namespace: ghost
type: Opaque
stringData:
    database__connection__user: ENC[AES256_GCM,data:Ry5wZZI=,iv:4pB2MM9pZ8kHoE8ayab1gD6hdahHvbWRPUcmvvsq7J0=,tag:LA64pDvzeTXIvW0JJ9H8ZA==,type:str]
    database__connection__password: ENC[AES256_GCM,data:ZeI1QOyH2qYChhlfjRU=,iv:XYcuvIxoSYCIeRwzcZ9GwS+VhJvH45kcdu5Z1oEO1+Q=,tag:NUbYhJZaauLRxoTwkvgJNw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d1VXVFE1aERvcVlpbTV3
            UjloRWZ4b21tdDB2S09zYXlYOVFMQWtjVlF3CnhHOVpKL3lhd29YZ29ST3MxYVl5
            QjBJcncxTGRnbWJ5VkZxVzlIVUkyNVkKLS0tIEh1U2RGMkZhanhrN284Ny9Vamo2
            TWhqYmtrRy8zS05NSnBYK2RuWlM2d3cKURDW74ZEILf6KOerL8fD3taQFKKIe9ws
            muaceGt3hMAp5GxDkfpun7EWsBRHVYaFfTlEOYxu+3yMHSMjuyIUGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T03:13:14Z"
    mac: ENC[AES256_GCM,data:wqyLoi1pgxeTokIy9hgJfN6hd+tqQmnY7txIVljNrEzBw+zXjeHrdBfkl4hAJ/bZ2jL3HQpV+1QkpQ5IlZytj24x27MRK4HfdsKLN5Ki+mfIp8jUfYtkpzAHM1gmcwupDxJomX/mAJg5At0wxZ1UVFf+cpgS9ToBrBhRuRoeC3E=,iv:RTFBEuf1zeCMKTLxw33/dGJH1EuNjQ/ThiT31OSTtQg=,tag:MmOPFQWlOnGce5Q0OMZLBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
