apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost
spec:
  selector:
    app: ghost
  ports:
    - name: http
      port: 2368     
      targetPort: 2368
      protocol: TCP
  type: ClusterIP
