apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: wizarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizarr
  template:
    metadata:
      labels:
        app: wizarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      containers:
      - name: wizarr
        image: ghcr.io/wizarrrr/wizarr:latest
        ports:
        - containerPort: 5690
          name: web
        env:
        - name: BASE_URL
          value: "https://plex-invite.alarlab.dev"
        - name: TZ
          value: "America/Denver"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        # - name: DB_HOSTNAME
        #   value: "192.168.1.15"
        # - name: DB_PORT
        #   value: "30432"
        # - name: DB_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: wizarr-secret
        #       key: POSTGRES_USER
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: wizarr-secret
        #       key: POSTGRES_PASSWORD 
        # - name: DB_NAME 
        #   value: "wizarr"
        volumeMounts:
        - name: config
          mountPath: /data/database
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wizarr-config-pvc