apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mysql
  name: mysql-data
spec:
  storageClassName: ""
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi