apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: mysql
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:l1abs5WFSNdvjMPKPig=,iv:VAm3hFRpme46vavpS2ujOQr3HJg909ksc6Penjlyz8s=,tag:L2BKS2py2PjGiaBOXZGYsQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:2JP4dCI=,iv:XkH8Xg8tLoVIJgr9Y09PrjJzGpz4u71P4DLDucdW+/Q=,tag:idm5/XZQLx8TXhbquIxt5w==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:umSrls4=,iv:b5kuXg0scESzZ/vKpE41ZqAUbYtiJn8vdRhnCFyuwT0=,tag:zM5bxBKAv0VGtTAnbwgKNQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:Ok1myZlYwo9bOnGUKl8=,iv:00mMXRXbXccmCgjg2XUiflNW5h4rokS+NKOhcOyajGI=,tag:u3zKugK3U30S23csJrOVwQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVzdYMW9WRGppYW5hUXVZ
            MjZMU3l1TENFQ0tCUzVSdk91THdJZ3dSNVVRCkJLczIrWSt6N1RTcC96aGVUUGIz
            cG0weVJtVGRmQWI3NUNQb0tNMXpETlUKLS0tIGhiMmE4NEF1TmRZNHVRU1hNdmpy
            bVlEM0U3Tk1YaHFWc3djMURqbTJNNEUKS/x/Zsj9zW4yImYrXlPeBc/Ch3Ar78xp
            FNKAr8TMeM0CRfsq8Y3M4v9S/4ay8wjOOsGghOwxP2n//CoJypUdCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T16:16:41Z"
    mac: ENC[AES256_GCM,data:mlSc9r8OzFQBCPF0zBZjnEIL/gwFwO2rk0vS8aNE8XkotuqhOUzqujc5zn6PBs/INAepgOuP0r4kXx8RsCxkjxkJzLH8t9KGOw/lLnISEhY6XhhyQ3pm6lhM5J7C1Ux0Cv/QJTzJoO309NFO+Dq8CGIze/PnIEevpjPI0jr+7Kk=,iv:EF/i/f1PQAdttOpl4xgCFn3d5wYgtcW5oTpBUeCBGBE=,tag:g6CCB8kmu4xzZgrDj2Xl6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
