apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: mysql
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:OBrwp4KU4YEbK3Om4J8=,iv:3PLvObTks4HEfvK11+Hc4LC8JQhzsZghcZag34ZBYrs=,tag:FHc5hX87n6XQDM1VFn2Ufg==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:edE3U3g=,iv:+5lt5JlIijijWa9eohyl5iSYcpdmt/bv8aS7A4Nfo28=,tag:f2XlMM7+D8d1p4hHI6JkCg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:2UEJIvc=,iv:wUgPyFkU8o9omvnuLFlDAH1wygPKcugWvdk57zc2eks=,tag:kJzFpFRkKEnrTGACT8oHTg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:9IwltTn6HFV8y54bkhs=,iv:bNbnEi1F3RYUUGgWrU0YvhsG6YpcjVUHZ977Zy9+xn4=,tag:xGYAZPeevF+OCpyxE9ksAQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bVJ6YU5oL1NRMDBwMWFq
            cmQ3eGJKMXBFaFVvWmF1elRhdGpFbHdLOFU0Cjc4bGJSaCtNZHF3YlNTUlRWVlFW
            ZFQ2dWY3RklIRHRCTENHbTd1Wk9tRWMKLS0tIG1xOEtDZ3VYclVNTEw5aXFqdGxJ
            b2NRNjBkSFlRelp4RE9HWXV1eno0U0UKvoiHhmWd7MkW4yDitsO109dqCearvAl0
            +z9A2pU8UAS+CdJQfjCsRjB8KhF89PX6VCqGmlKtnIYYmFYYbUIATQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:25:04Z"
    mac: ENC[AES256_GCM,data:3HZCJWM9NrTui3mzv4W1jvQfAUkqfYS/8ZGhwqtLU1ChTv0rsiqeBqKd90a3oTJRbPqQm57Rx7WmFxobbePk7v3F8f+N/0w0eRBSlPfEas5n/g4AqFZP+UdZYpkcr8RcWbqt/PqATQ/aNKQQT68InO+9z4K5lZdgGduYKrIfExk=,iv:X/0FVO7GqkOPQqM8ZssE4s2EnC6cefP0fHKyQ5C+tbA=,tag:vOClxKz5CWWkSkrfDPdfdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
