apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: ddns-updater
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:MjT8d9VjQ2rBWNx9Pv5ZzqrL6E3uek3D6CJxfmWH5fkr8aOfJdS3dR4Ajn2sEs0aKlKFC5vtgkl8O9unxna4zSYs5aO62LgUr50mX7LA/06BfGZVpPgMkRN9hURLxgoc4ciqtS1dBiYS48ibG5MUIVZzVo/URFZNBYd1mEg74BMxUh0Z/Xt+0pUnGhp6b2fwK9AymYHWKX1IiciPDcv7vRBfusvIcwdLh7Bbt5/zvF0ka5JGv2oNItim25CEhSWkEg4/pKnVPObWJ25Fz06o2AiSUBfG/k+EH7VWsXs/PXY85PByGUv2OOsGmuKI7Kzpooesb6q6LqmSnpsCQx0kUZOU9uIxfRTVrl3plwC0vxNKFkW8wu2tN98LE6RqIdiP7H1SLxznPudD/57cVlwbZ5UdO6wg/fITJ0OHAmmNgww9cEUJt98J9VDo9cc9PnQ0kAOnRkZ6hf8TZCU4N0+jIX9SDFcLGk7FEKP4JWnKaN6qA3vMK5NjWWr25nir9lpERr5W1u9PJdg/zCaof9TbRJlC6S1glm4SIPYX3Q/geXCJV+kN7nGutRNVqzqmeqrcsf7iSr7+I8poeVjWpbAgtpkvKe+v7T2R2MatJbmgl/T+bWbi0aERjgqqXCUpADHuYXNQiAIuR4/SFAuNxt+ioxlvFGKQkFYqn+dYBzAU1mfJa3Pmqx/ry8YMce0TPRoS3K2sSfSWwocED6pJR9DJs+Den2gBiwrN0G91RRkmTEv/SG99XCCSDdTQYf6ydoqnoOaqD7tFv6pJIpChDDvF+WNVQmyw,iv:5yq11naW5vo1wFWmhlc7kSsgngdEMeIw5J8AQqbLt8A=,tag:39AEPJNS7wSgTqMOC6vRHQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVURqTUpIU1cvUFlvZXRF
            YzlRRDkvUnBzbHRwNGdleDI3dVloZmxDbjJnCkw0a1E3MGdOcDJGcVBDeFpOaVA2
            bEZTYk1CRUJCcCs0Nk1kaGFGSjJHd0EKLS0tIE9EeVQ3OGVTRnplZXhjR3R4bnd5
            MU5NMW9TdGFOYW55d0plOXJKVFVVYm8KGVltkun8XQClPyqRUB+caY/wfsh31LMQ
            ALYsbgmKNu2uaCmBwTIgJCDv7Fh6Jd4hdU4Un74s2f4P1tZ8NBvGMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:53:23Z"
    mac: ENC[AES256_GCM,data:DGt+3BhO5ZMOWWDfjAvQ99nIGJWCfQxWgrKMWqJxDo3OyPVJy1OamR/Zx3xcXMT4jGKoKS/uZwxZ751A7OzYmScwDgXQPCz+4KWpIaWURTnrh3u5LjsifNXPFAVvPi6CH8bOiX1YODhO6/5UMMBN+gYRwcAubw3Irc5BxKt0yTc=,iv:ojKI0kTN35kVdRK+5RHuZKr5D8zxRqB4uYwm9SsR5qg=,tag:0VihgF71+Oz06ClWeRx77w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
