apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: mealie
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:QMh5vLX7,iv:BLQFehwbRrV9lLeP3A8B/feKmlyGg3YVG6owvrFUZCs=,tag:ylK2FUu5UwVJTldThsM9lg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ThAoIPygecugVikf,iv:3GsP02xdEsoJgLlDUXN/4dZU5CH2vVKJmwq3FI3sj4Q=,tag:XS05sj15a4pAkY/TOfmIwA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:8WKVK0fGMXCw2aMRlZ1MHrZo,iv:AL/3G9JDGFkMmqVxJCAh4209+llA239up6qatxuhcEA=,tag:WuFDXpd/aSyBfQu662Mqig==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xxDqoqF3Ga6dbZIAm+L7jHJlXQ==,iv:JxN/LiusSfqFL1ZQY+aJiefA6Z+tlcGSt+tv1EsrAJ0=,tag:sZdwilE57SvJXhU5ZCgNyw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT1JSNjVuVWFKYVU2azdY
            UmliVHduRlZoVFFLaDcrV0VLZHlBWkxvekNRCmUzdE9mMXNXWUlOeTZZRlJIOGVj
            ZHRteTRVMi9Ca2I3WTlTRGs2VlgvVUEKLS0tIExnejR2b1BuckNyVUJnbDFTamJu
            azhTT2MwdHpaV2pXb3RGN3lCMCtYS0kKFzhUWYDV9f+Eh1RNPsoQo4QR6FddqksF
            nECKLcKDvXalyb2QwctgD0IDy/3jZ8wqa2tGN/JnuZg3pAZja3PHQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T13:49:44Z"
    mac: ENC[AES256_GCM,data:stlnT8BQ0R6LJoU5cdsG+oTf9PMrv5KE4VyZbN8oIWiTSksN4e5QxZfJtYH6rZE0bzpQOhhbXJEnntm0pXisJVgvjUhL7ZSo7bGyFI4yFTnQUsG6mewsyoxIk63P15F7QxJTLfardnZLRczrmo+HGUGiUSsLXd4PU8TnSwgzwvw=,iv:HKuR5A/8Yoiqk2Q0bNxsgmTr4uxG5WjTQ6SDKOh+Vn8=,tag:mC/kCAOJh0cdRTxibKkJ7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
