apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
type: Opaque
data:
    apiKey: ENC[AES256_GCM,data:5FBV62HLFxQ3ixdYNaUBJXnOVxxWiH7DGi0pvMZhSzKHveSREFWay7E/spMWYlkfLJZjl0EfoDs=,iv:YrsN3iq+soRRr4TlQXrYOFzcwIzsDURaU3KroDN1TBU=,tag:PCl+Osy7lBvoNeAeOmYVtQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbUUzUmRXNFdmWWJ6MHQr
            S09BMlVsclJrd3MzU213anRtYlNXS3JoZVI0CjAraHU5RUlKbGZEeEU4U3JtWXdq
            MEN0RTB1WWUxTjVrZmwrNi9SUGU5Y3cKLS0tIGVLYUpIaDRRUXJTU2tkLytGNHBT
            Unovc21OVXlRMldlSXkwd1BPZUEzaUUK+Ywz3lZvGAR+TDM0NJ0kgydLmC8xKh9Z
            LiMMaA7BDdrw7g+SmZb9hOP6dxZzuJJcFhmAVlkp9KVznHZwF2enng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:58:15Z"
    mac: ENC[AES256_GCM,data:IdP7R34vMPRhuA9aBZTizNGSWHlRdsqZK5BggNYdvIVVabmdaJRoHQ/kRyMzpbv70tkyp3nLaUBcgjanJWcjEffdkcR3oYo7cePd/bmLTkViS1XcVWEM1aNWaS932pIJFCD9sr2idND6ax8X7lNgU8qxqDm9JSjEAQPiGHkwdxQ=,iv:l3U1Xig4WLyvwPCFoIvkJFm9KPhlkDoE2WcilrKIEdM=,tag:2NCAsgiP8xxp2NOdEppXxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
