apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
type: Opaque
data:
    apiKey: ENC[AES256_GCM,data:stM+wNbuI7/hQrklj4qWE5f0yYF+W1CDnxji4K/By06XwZaIGkUFPcVXZCCk5dWLc4aSzEJ+Oq0=,iv:5sAG2AGfYJxQ2hl7BNZGw3Vj3j7/Nq6EdjMkvgrchE0=,tag:TSmOpvLL/eXldmMvVpN0FA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN2dHdk83aW0ycDlwT0N5
            bkpGd3NraW5ueit6L3Z6bXJjdnAxMlcwdTJBCjFnVTQ2UWNiczlGeTh4Ky9xdkVO
            QnBJRkY4aVdsaVFIa0FFQ3FjOVd6V1UKLS0tIGVzM0U2WURTOFZHZEpyeWlHOUVh
            dlRSZHVKazJWNFh4bkMyV21mOVZTRlUK4haPVosdlpAW1QYWKKK5uOb+oE+2drsG
            1PbucGI6d/SEi0d/VKrpU5EkNr5gr0YYc8J8lxBl241o73WuoeCF2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:55:12Z"
    mac: ENC[AES256_GCM,data:fAAigZthTLY2Zcq3eHg/h27LyOnFIMu1bbp9kHKDVhRpn8ttjvQeAsd2H3daO65QayWFUsPojH63J3ztrgY7ks89ppJ3qaEFDSOAZSNXparmCFMy5ehFghe2Gn9ewA+UMQ7cM3lu0o4D+2ka8Cfpd/bMa9R8p0OIO50Ea1Gstuk=,iv:7C88cS2ISWoGemyrlOMJ+Fp4TfGBbqpaYiy0vWps2nU=,tag:EdkwDLz4G7fTpifE4F0YuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
