apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
type: Opaque
data:
    apiKey: ENC[AES256_GCM,data:+Zoi9YkR9l0YinW/RaXCIwEoZEskVizUEo1aH81X0/EJpTasiTRDZTD4QRCQ8D8usDoUmQCooUM=,iv:V20FXluD4DYwgs5aM1fCfk/kHbIbJ4/Dg4Eh/tUGA/I=,tag:RfYi5Dt0qY10Vs5FpiXvOA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVhoYXB4alFQOTRZZE9H
            cnZESjNkYmZLYTRjQ000eFZucGNzQkNaWGtRCnRENG8wSyswRm54czN4TUlyYmZw
            cmxJTUJtdGNzdHlTMDd6WlF6MG9MU1UKLS0tIEFaakovc0lzb3gyRGlIQTZhVnpm
            eVF3SitLWlNKa1E5cmNiL0xIWmpQWHcKJdCT9m0kuerpshDfZX9xbV9e9JwxDoIh
            7oye/Ja6C1yQrNCFCOjbGxvvRLIeFKZYsPTaJ22cGsh5jOHjeYI/og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T00:57:08Z"
    mac: ENC[AES256_GCM,data:6H0FzBqcYjkJXKOG7VRQE2qomPa+5cDC8EeBUP0iZJJlZ4N6wGzo04sM/iqOrfcuVvnCx3GPbT0UE8kFj6h5s4Tbgjo6av6yY3ZaeDEpsyJ86qGpRe6UWUCJ0+ja+yO9wT3GZdnf15Hvjx2CxDonYC3Bq9VtZd4Zi/PIdek8Uyw=,iv:cnL3C3AazsfBVXQBjdZTM+syqbLrkEVzx3Q3AeBDdqw=,tag:IJb+o0fgPqlSU/2sEVdhTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
